#ifndef QTGRADIENTEDITOR_GLOBAL_H
#define QTGRADIENTEDITOR_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(QTGRADIENTEDITOR_LIBRARY)
#    define QTGRADIENTEDITOR_EXPORT Q_DECL_EXPORT
#else
#    define QTGRADIENTEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // QTGRADIENTEDITOR_GLOBAL_H
